import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  vi: { translation: {
    nav: { assistant: "Trợ lý AI", library: "Thư viện", documents: "Quản trị tài liệu", evaluation: "Đánh giá", access: "Demo phân quyền" },
    common: { search: "Tìm kiếm", filter: "Bộ lọc", all: "Tất cả", reset: "Đặt lại dữ liệu", save: "Lưu thay đổi", cancel: "Hủy", close: "Đóng", view: "Xem chi tiết", status: "Trạng thái", department: "Phòng ban", classification: "Phân loại", role: "Vai trò", language: "English", citations: "Nguồn tham chiếu", documents: "tài liệu", active: "Đang hoạt động", archived: "Đã lưu trữ" },
    assistant: { title: "Hỏi tri thức doanh nghiệp", subtitle: "Câu trả lời có kiểm chứng, giới hạn theo quyền của từng người dùng.", placeholder: "Hỏi về chính sách, quy trình hoặc tài liệu...", send: "Gửi câu hỏi", newChat: "Cuộc trò chuyện mới", history: "Lịch sử", suggestions: "Gợi ý để bắt đầu", empty: "Bạn muốn tìm hiểu điều gì?", denied: "Bạn không có quyền truy cập thông tin cần thiết để trả lời câu hỏi này.", insufficient: "Không tìm thấy đủ bằng chứng trong kho tri thức được phép truy cập để đưa ra câu trả lời đáng tin cậy.", stages: { permission: "Đang kiểm tra quyền truy cập", searching: "Đang tìm nguồn phù hợp", synthesizing: "Đang tổng hợp câu trả lời", validating: "Đang xác thực trích dẫn" } },
    library: { title: "Thư viện tri thức", subtitle: "Khám phá tài liệu phù hợp với quyền truy cập hiện tại.", accessible: "Có quyền truy cập", locked: "Không có quyền", noResults: "Không có tài liệu phù hợp", accessNote: "Quyền truy cập được tính theo persona hiện tại." },
    admin: { title: "Quản trị tài liệu", subtitle: "Tải lên, phân loại và theo dõi ingestion trong một nơi.", upload: "Tải tài liệu", edit: "Sửa metadata", archive: "Lưu trữ", file: "Tên tệp", titleField: "Tiêu đề tài liệu", ingestion: "Ingestion gần đây", queued: "Đang chờ", extracting: "Đang trích xuất", indexing: "Đang lập chỉ mục", ready: "Sẵn sàng", adminOnly: "Chuyển sang persona Knowledge Admin để quản trị tài liệu." },
    evaluation: { title: "Evaluation dashboard", subtitle: "Theo dõi độ chính xác permission trên toàn bộ public dataset.", run: "Chạy lại 50 cases", total: "Tổng số cases", allow: "Allow kỳ vọng", deny: "Deny kỳ vọng", passRate: "Tỷ lệ đạt", result: "Kết quả", passed: "Đạt", failed: "Lỗi", running: "Đang chạy evaluation..." },
    access: { title: "Phòng lab phân quyền", subtitle: "So sánh cùng một câu hỏi qua nhiều vai trò và phòng ban.", matrix: "Ma trận truy cập", simulator: "So sánh persona", run: "Chạy so sánh", allowed: "Được phép", denied: "Bị từ chối", own: "Cùng phòng ban" },
  } },
  en: { translation: {
    nav: { assistant: "AI Assistant", library: "Library", documents: "Document admin", evaluation: "Evaluation", access: "Access-control demo" },
    common: { search: "Search", filter: "Filters", all: "All", reset: "Reset dataset", save: "Save changes", cancel: "Cancel", close: "Close", view: "View details", status: "Status", department: "Department", classification: "Classification", role: "Role", language: "Tiếng Việt", citations: "Citations", documents: "documents", active: "Active", archived: "Archived" },
    assistant: { title: "Ask enterprise knowledge", subtitle: "Evidence-backed answers scoped to each user's access.", placeholder: "Ask about a policy, process, or document...", send: "Send question", newChat: "New conversation", history: "History", suggestions: "Suggested questions", empty: "What would you like to know?", denied: "You do not have access to the information required to answer this question.", insufficient: "There is not enough evidence in the knowledge you can access to provide a reliable answer.", stages: { permission: "Checking access permissions", searching: "Finding relevant sources", synthesizing: "Synthesizing the answer", validating: "Validating citations" } },
    library: { title: "Knowledge library", subtitle: "Explore documents available to your current access profile.", accessible: "Accessible", locked: "No access", noResults: "No matching documents", accessNote: "Access is calculated for the current persona." },
    admin: { title: "Document administration", subtitle: "Upload, classify, and follow ingestion in one place.", upload: "Upload document", edit: "Edit metadata", archive: "Archive", file: "File name", titleField: "Document title", ingestion: "Recent ingestion", queued: "Queued", extracting: "Extracting", indexing: "Indexing", ready: "Ready", adminOnly: "Switch to the Knowledge Admin persona to manage documents." },
    evaluation: { title: "Evaluation dashboard", subtitle: "Track permission accuracy across the public dataset.", run: "Run all 50 cases", total: "Total cases", allow: "Expected allow", deny: "Expected deny", passRate: "Pass rate", result: "Result", passed: "Passed", failed: "Failed", running: "Running evaluation..." },
    access: { title: "Access-control lab", subtitle: "Compare the same question across roles and departments.", matrix: "Access matrix", simulator: "Persona comparison", run: "Run comparison", allowed: "Allowed", denied: "Denied", own: "Own department" },
  } },
};

i18n.use(initReactI18next).init({ resources, lng: localStorage.getItem("tasco-language") || "vi", fallbackLng: "vi", interpolation: { escapeValue: false } });
export default i18n;
